# Generated by Django 3.2.9 on 2021-11-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamplePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='example_examplepluginmodel', serialize=False, to='cms.cmsplugin')),
                ('content', models.TextField(blank=True, default='', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Example Plugin Model',
                'verbose_name_plural': 'Example Plugin Models',
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
