BASE_STRUCTURE_VARIANT_CLASS_DIV = 'div'
BASE_STRUCTURE_VARIANT_CLASS_ARTICLE = 'article'
BASE_STRUCTURE_VARIANT_CLASS_SECTION = 'section'
BASE_STRUCTURE_VARIANT_CLASS_HEADER = 'header'
BASE_STRUCTURE_VARIANT_CLASS_FOOTER = 'footer'
BASE_STRUCTURE_VARIANT_CLASS_ASIDE = 'aside'

BASE_STRUCTURE_VARIANT_CLASSES_CHOICES = (
    (BASE_STRUCTURE_VARIANT_CLASS_DIV, 'div'),
    (BASE_STRUCTURE_VARIANT_CLASS_ARTICLE, 'article'),
    (BASE_STRUCTURE_VARIANT_CLASS_SECTION, 'section'),
    (BASE_STRUCTURE_VARIANT_CLASS_HEADER, 'header'),
    (BASE_STRUCTURE_VARIANT_CLASS_FOOTER, 'footer'),
    (BASE_STRUCTURE_VARIANT_CLASS_ASIDE, 'aside'),
)

VARIANT_GRID_CONTAINER_CLASS_NO_CONTAINER = "no-container"
VARIANT_GRID_CONTAINER_CLASS_BOXED = "container"
VARIANT_GRID_CONTAINER_CLASS_FLUID_UNTIL_SM = "container-sm"
VARIANT_GRID_CONTAINER_CLASS_FLUID_UNTIL_MD = "container-md"
VARIANT_GRID_CONTAINER_CLASS_FLUID_UNTIL_LG = "container-lg"
VARIANT_GRID_CONTAINER_CLASS_FLUID_UNTIL_XL = "container-xl"
VARIANT_GRID_CONTAINER_CLASS_TOTALLY_FLUID = "container-fluid"

VARIANT_GRID_CONTAINER_CLASS_CHOICES = (
    (VARIANT_GRID_CONTAINER_CLASS_NO_CONTAINER, "No container only for bg"),
    (VARIANT_GRID_CONTAINER_CLASS_BOXED, "Boxed"),
    (VARIANT_GRID_CONTAINER_CLASS_FLUID_UNTIL_SM, "Fluid until sm"),
    (VARIANT_GRID_CONTAINER_CLASS_FLUID_UNTIL_MD, "Fluid until md"),
    (VARIANT_GRID_CONTAINER_CLASS_FLUID_UNTIL_LG, "Fluid until lg"),
    (VARIANT_GRID_CONTAINER_CLASS_FLUID_UNTIL_XL, "Fluid until xl"),
    (VARIANT_GRID_CONTAINER_CLASS_TOTALLY_FLUID, "Totally fluid"),
)

TAG_TYPE_SECTION = "section"
TAG_TYPE_DIV = "div"

TAG_TYPE_GRID_CONTAINER_CLASS_CHOICES = (
    (TAG_TYPE_SECTION, "Section"),
    (TAG_TYPE_DIV, "Div"),
)


VARIANT_GRID_ROW_CLASS_LEFT = "start"
VARIANT_GRID_ROW_CLASS_CENTER = "center"
VARIANT_GRID_ROW_CLASS_RIGHT = "end"
VARIANT_GRID_ROW_CLASS_AROUND = "around"
VARIANT_GRID_ROW_CLASS_BETWEEN = "between"

VARIANT_GRID_ROW_CLASSES_CHOICES = (
    (VARIANT_GRID_ROW_CLASS_LEFT, "Align left"),
    (VARIANT_GRID_ROW_CLASS_CENTER, "Align center"),
    (VARIANT_GRID_ROW_CLASS_RIGHT, "Align right"),
    (VARIANT_GRID_ROW_CLASS_AROUND, "Align around"),
    (VARIANT_GRID_ROW_CLASS_BETWEEN, "Align between")
)
