# Generated by Django 3.2.7 on 2021-09-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_grid_builder', '0002_rename_cols_gridcolpluginmodel_cols_xs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gridrowpluginmodel',
            old_name='variant',
            new_name='variant_class',
        ),
    ]
