# Generated by Django 3.2.7 on 2021-09-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_grid_builder', '0003_rename_variant_gridrowpluginmodel_variant_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basestructurepluginmodel',
            name='variant_class',
        ),
        migrations.AddField(
            model_name='basestructurepluginmodel',
            name='tag_type',
            field=models.CharField(choices=[('div', 'div'), ('article', 'article'), ('section', 'section'), ('header', 'header'), ('footer', 'footer'), ('aside', 'aside')], default='div', max_length=64, verbose_name='Tag Type'),
        ),
    ]
